// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckRootStatus():Promise<Record<string, any>>;

export function CheckTools():Promise<Array<main.ToolStatus>>;

export function ClearRootPassword():Promise<boolean>;

export function DetectInputType(arg1:string):Promise<main.InputType>;

export function DoHarden(arg1:main.HardenRequest):Promise<main.HardenResponse>;

export function ExecuteFunction(arg1:string,arg2:string):Promise<main.ExecuteResult>;

export function GetContainerDetail(arg1:string):Promise<main.ContainerDetailResult>;

export function GetFunctions(arg1:string):Promise<Array<main.FunctionItem>>;

export function GetHardenContainers():Promise<Array<main.HardenContainer>>;

export function HasRootPassword():Promise<boolean>;

export function InstallTool(arg1:string):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ScanContainers(arg1:string):Promise<main.ContainerScanResult>;

export function SetRootPassword(arg1:string):Promise<boolean>;
