// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRootStatus() {
  return window['go']['main']['App']['CheckRootStatus']();
}

export function CheckTools() {
  return window['go']['main']['App']['CheckTools']();
}

export function ClearRootPassword() {
  return window['go']['main']['App']['ClearRootPassword']();
}

export function DetectInputType(arg1) {
  return window['go']['main']['App']['DetectInputType'](arg1);
}

export function DoHarden(arg1) {
  return window['go']['main']['App']['DoHarden'](arg1);
}

export function ExecuteFunction(arg1, arg2) {
  return window['go']['main']['App']['ExecuteFunction'](arg1, arg2);
}

export function GetContainerDetail(arg1) {
  return window['go']['main']['App']['GetContainerDetail'](arg1);
}

export function GetFunctions(arg1) {
  return window['go']['main']['App']['GetFunctions'](arg1);
}

export function GetHardenContainers() {
  return window['go']['main']['App']['GetHardenContainers']();
}

export function HasRootPassword() {
  return window['go']['main']['App']['HasRootPassword']();
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ScanContainers(arg1) {
  return window['go']['main']['App']['ScanContainers'](arg1);
}

export function SetRootPassword(arg1) {
  return window['go']['main']['App']['SetRootPassword'](arg1);
}
